// 08-svelte/src/App.svelte
<script>
  const apiBaseUrl = "https://jsonplaceholder.typicode.com";

  let Resources = {
    POSTS: "posts",
    USERS: "users",
    COMMENTS: "comments",
  };

  let currentResource = undefined;
  let data = [];
  let name = "roshane";
  let isLoading = false;

  let count = 0;

  const fetchResource = ({ resource }) => {
    currentResource = resource;
    isLoading = true;
    console.log("fetching resources for", resource);
    let url = `${apiBaseUrl}/${resource}`;
    fetch(url)
      .then((data) => data.json())
      .then((json) => {
        data = json;
        isLoading = false;
      });
  };
</script>

<div>
  <p on:click={() => (count += 1)}>Hello {name}</p>

  <span>you clicked {count} times</span>

  <hr />

  {#each Object.keys(Resources) as k}
    <button on:click={() => fetchResource({ resource: Resources[k] })}>
      {k}
    </button>
  {/each}

  {#if isLoading}
    <p>Loading...</p>
  {/if}

  {#if !isLoading}
    {#each data as i}
      <pre>{JSON.stringify(i)}</pre>
    {/each}
  {/if}
</div>

// 06-webpack-react-ts/src/components/App.tsx
import * as React from 'react';

export interface RevenueInput {
    amount: number,
    name?: string
}

const onClickTitle = (e: any) => {
    console.log('title clicked ', e);
    calculateRevenue({ amount: 1000 });
}

const calculateRevenue = (input: RevenueInput) => {
    console.log('calculating the revenue ');
}

const App = () => {
    const [resource, setResourceType] = React.useState<string>();
    const [isLoading, setLoading] = React.useState<boolean>(false);
    const [data, setData] = React.useState<any[]>([]);

    React.useEffect(() => {
        if (resource) {
            setLoading(true);
            fetch(`https://jsonplaceholder.typicode.com/${resource}`)
                .then(data => data.json())
                .then(json => setData(json))
                .then(ignore => setLoading(false));
        }
    }, [resource]);

    return (
        <div>
            <div>
                <button onClick={() => setResourceType('posts')}>posts</button>
                <button onClick={() => setResourceType('comments')}>comments</button>
                <button onClick={() => setResourceType('todos')}>todos</button>
            </div>
            <p> {resource}</p> {isLoading && <h2>Loading...</h2>}

            <hr />
            {
                !isLoading && data.map(json => <pre>{JSON.stringify(json)}</pre>)
            }


            <p onClick={onClickTitle}>This is the name of the element I was referring to</p>
        </div>
    );
}

export default App;
